PlantifyControlPanel/ControlPanel.PLL/Controllers/RoleController.cs
using AutoMapper;
using ControlPanel.DAL.Models;
using ControlPanel.PLL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ControlPanel.PLL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IMapper mapper;

        public RoleController(RoleManager<IdentityRole> roleManager,IMapper mapper)
        {
            this.roleManager = roleManager;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var mappedRole = roleManager.Roles.Select(r => new RoleViewModel()
                {
                  Id=r.Id,
                  RoleName = r.Name,
                }).ToList();
                return View(mappedRole);
            }
            else
            {
                var role = await roleManager.FindByNameAsync(name);
                if (role is not null)
                {

                    var mappedRole = new RoleViewModel()
                    {
                       Id= role.Id,
                       RoleName = role.Name
                    };
                    return View(new List<RoleViewModel>() { mappedRole });
                }

                return View(new List<RoleViewModel>() { });

            }


        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(RoleViewModel RoleVM)
        {

            if (ModelState.IsValid)
            {
                var MappedRole = mapper.Map<RoleViewModel, IdentityRole>(RoleVM);
                await roleManager.CreateAsync(MappedRole);


                return RedirectToAction(nameof(Index));
            }

            else
                return View(RoleVM);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id, string name = "Update")
        {
            if (id is null)
                return BadRequest();

            var role = await roleManager.FindByIdAsync(id);
            var mappedrole = mapper.Map<IdentityRole, RoleViewModel>(role);

            return View(name, mappedrole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromRoute] string id, RoleViewModel roleVM)
        {
            if (id != roleVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await roleManager.FindByIdAsync(id);
                    role.Name = roleVM.RoleName;
                    role.Id = roleVM.Id;


                    var result = await roleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {

                        ModelState.AddModelError(string.Empty, "Failed Updated ! ");
                        return View(roleVM);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            return View(roleVM);


        }
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Update(id, "Delete");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, RoleViewModel roleVM)
        {

            if (id != roleVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(id);
                var result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Faid To Update");

                }
            }

            return View(roleVM);
        }





    }
}

PlantifyControlPanel/ControlPanel.PLL/Controllers/UserController.cs
using AutoMapper;
using ControlPanel.DAL.Models;
using ControlPanel.PLL.ViewModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Plugins;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace ControlPanel.PLL.Controllers
{
    [Authorize]
  
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IMapper mapper;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<ApplicationUser> userManager ,SignInManager<ApplicationUser> signInManager,IMapper mapper,RoleManager<IdentityRole>roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.mapper = mapper;
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string username)
       {



            var userName = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                var mappedUsers =  userManager.Users.Select( u => new UserViewModel()
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    Email = u.Email,
                    Roles = userManager.GetRolesAsync(u).Result
                }).ToList();
                return View(mappedUsers);
            }
            else
            {
                var user=await userManager.FindByNameAsync(username);
                if (user is not null)
                {

                    var mappeduser = new UserViewModel()
                    {
                        Id = user.Id,
                        UserName = user.UserName,
                        Email = user.Email,
                        Roles = userManager.GetRolesAsync(user).Result
                    };
                    return View(new List<UserViewModel>() { mappeduser });
                }

                return View(new List<UserViewModel>() {  });

            }


            
            

        }

        [HttpGet]
        public IActionResult Create()
        {


         


            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(UserViewModel userVM)
        {
           
            if (ModelState.IsValid)
            {
                var check = await userManager.FindByEmailAsync(userVM.Email);
                if (check is null)
                {
                    
                    var mappeduser =mapper.Map<UserViewModel,ApplicationUser>(userVM);

                    if (userVM.Roles != null && userVM.Roles.Any())
                    {
                        foreach (var roleName in userVM.Roles)
                        {
                            if (roleManager.Roles.Any(r => r.Name == roleName))
                            {
                                var role = roleManager.Roles.FirstOrDefault(r => r.Name == roleName);
                                await userManager.AddToRoleAsync(mappeduser, role.Name);
                            }
                        }
                    }


                    var result = await userManager.CreateAsync(mappeduser,"P@asswo0rd");

                    if (result.Succeeded)
                    {

                        return RedirectToAction(nameof(Index));
                    }

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                ModelState.AddModelError(String.Empty, "The Email is already taken");
            }

            userVM.AllRoles = await roleManager.Roles.Select(r => r.Name).ToListAsync();


            return View(userVM);
        }



        [HttpGet]
        public async  Task<IActionResult> Update(string id,string name="Update")
        {
            if (id is null)
                return BadRequest();

            var user = await userManager.FindByIdAsync(id);
           
            var mappeduser = mapper.Map<ApplicationUser, UserViewModel>(user);
            mappeduser.AllRoles = await roleManager.Roles.Select(r => r.Name).ToListAsync();
            mappeduser.Roles = await userManager.GetRolesAsync(user);
            
            return View(name,mappeduser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromRoute] string id ,UserViewModel userVM)
        {
            if (id != userVM.Id)
                return BadRequest();
            userVM.AllRoles = await roleManager.Roles.Select(r => r.Name).ToListAsync();
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await userManager.FindByIdAsync(id);
                    user.UserName = userVM.UserName;
                    user.Email = userVM.Email;
                    user.SecurityStamp = Guid.NewGuid().ToString();


                    // Clear existing roles
                    var userRoles = await userManager.GetRolesAsync(user);
                    await userManager.RemoveFromRolesAsync(user, userRoles);

                    // Add the selected role
                    await userManager.AddToRoleAsync(user, string.Join(",",userVM.Roles));



                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                       
                        ModelState.AddModelError(string.Empty,"Failed Updated ! please reverse your data if its match already exists if falid!");
                        return View(userVM);
                    }
                }catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            return View(userVM);


        }
        [HttpGet]
        public async Task< IActionResult> Delete(string id)
        {
            return await Update(id,"Delete");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Delete(string id, UserViewModel userVM)
        {

            if(id !=userVM.Id)
                return BadRequest();
            if(ModelState.IsValid)
            {
                var user=await userManager.FindByIdAsync(id);
               var  result= await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Faid To Update");

                }
            }

            return View(userVM);
        }

        private List<SelectListItem> GetRolesList()
        {
            var roles = roleManager.Roles
                .Select(r => new SelectListItem { Value = r.Name })
                .ToList();

            return roles;
        }

    }
}

PlantifyControlPanel/ControlPanel.PLL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- base:css -->
    <link rel="stylesheet" href="../../vendors/typicons.font/font/typicons.css">
    <link rel="stylesheet" href="../../vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="../../images/favicon.png" />
    

</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                            <div class="brand-logo">
                                <img src="../../images/PlantifyLogo" alt="logo">
                            </div>




                                     <div>
                                        @RenderBody()
                                     </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="../../vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="../../js/off-canvas.js"></script>
    <script src="../../js/hoverable-collapse.js"></script>
    <script src="../../js/template.js"></script>
    <script src="../../js/settings.js"></script>
    <script src="../../js/todolist.js"></script>
    <script src="~/js/myjs/terms.js"></script>
    <!-- endinject -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ValidationScriptSection",required:false)
</body>
</html>

PlantifyControlPanel/ControlPanel.PLL/Views/Shared/_ButtonPartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a  asp-action="Update" asp-route-id="@Model"  ><i class="fas fa-edit"></i> </a>



<a asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>

@section Scripts{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="~/css2/stylesheet_userindex.css" rel="stylesheet" />
}

PlantifyControlPanel/ControlPanel.PLL/Views/Shared/_Layout.cshtml
@{
    var name =  User.Identity.Name; ;
}

<!DOCTYPE html>
<html lang="en">
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Plantify Admin Dashboard</title>
    <!-- base:css -->
    <link rel="stylesheet" href="~/vendors/typicons.font/font/typicons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" asp-controller="Home" asp-action="Index">
                    <img   
                    src="~/images/PlantifyLogo" alt="logo" />
                </a>
                <a class="navbar-brand brand-logo-mini" href="~/images/index.html"><img src="~/images/logo-mini.svg" alt="logo" /></a>
            <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex" type="button" data-toggle="minimize">
                <span class="typcn typcn-th-menu"></span>
            </button>
        </div>

        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item nav-profile dropdown">
                    <a class="nav-link dropdown-toggle  pl-0 pr-0" href="#" data-toggle="dropdown" id="profileDropdown">
                        <i class="typcn typcn-user-outline mr-0"></i>
                            <span class="nav-profile-name">@name</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                        <a asp-controller="Account" asp-action="Signout" class="dropdown-item">
                            <i class="typcn typcn-power text-primary"></i>
                            Logout
                        </a>
                    </div>
                </li>

            </ul>
        </div>

     </nav>
    <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close typcn typcn-delete-outline"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options" id="sidebar-light-theme">
                        <div class="img-ss rounded-circle bg-light border mr-3"></div>
                        Light
                    </div>
                    <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                        <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                        Dark
                    </div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles primary"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default border"></div>
                    </div>
                </div>
            </div>
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <div class="d-flex sidebar-profile">
                            <div class="sidebar-profile-name">
                                <p class="sidebar-name">
                                    @name
                                </p>
                                <p class="sidebar-designation">
                                    Welcome
                                </p>
                            </div>
                        </div>
                        <p class="sidebar-menu-title">Dash menu</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="true" aria-controls="auth">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Users</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse show" id="auth" style="">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="User" asp-action="Index">

                                        <span class="menu-title"> User List </span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="User" asp-action="Create">

                                        <span class="menu-title"> Create User </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="true" aria-controls="auth">
                            <i class="typcn typcn-document-text menu-icon"></i>
                            <span class="menu-title">Roles & Permissions</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse show" id="auth" style="">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Role" asp-action="Index">
                                       
                                        <span class="menu-title"> Roles List </span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Role" asp-action="Create">
       
                                        <span class="menu-title"> Create Role </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    
            </ul>
        </nav>
            
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

       
        </div>
</div>
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center ">
            <span class="text-center text-sm-left d-block d-sm-inline-block" style="justify-content:center;">All Copyright Reserved For Plantify ©  2024</span>
        </div>
    </footer>
    <!-- partial -->
    <!-- base:js -->
    <script src="~/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/js/off-canvas.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/template.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/todolist.js"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="~/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="~/js/dashboard.js"></script>
    <!-- End custom js for this page-->
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ValidationScriptSection",required:false)

</body>
</html>